image: ubuntu:24.04

definitions:
  steps:
    - step: &publish-step
        name: Manage Customisation Archive Publish
        max-time: 10
        script:
          - apt-get update && apt-get install -y curl zip unzip git
          - curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          - chmod +x /usr/local/bin/yq
          - yq --version
          - echo "Installing OpenShift CLI (oc)..."
          - curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz -o oc.tar.gz
          - tar -xvzf oc.tar.gz
          - mv oc kubectl /usr/local/bin/
          - oc version
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip awscliv2.zip
          - ./aws/install
          - aws --version
          - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          - aws configure set default.region ${AWS_DEFAULT_REGION:-eu-central-1}
          - chmod +x ./manage-cust-archive.sh
          - ./manage-cust-archive.sh $OCP_USERNAME $OCP_PASSWORD $OCP_SERVER_URL $AWS_BUCKET $AWS_BUCKET_URL
        artifacts:
          - build/**

pipelines:
  custom:
    manage-publish-dev:
      - step:
          <<: *publish-step
          deployment: DEV